### PR TITLE
Improvement for accounts.topocder.com

### PR DESCRIPTION
**Pull request by ykohata**
Related tasks:
- Enhance ng-auth to support other auth0 connections
  (https://app.asana.com/0/100297043256537/100297043256572)
  - Add the ability to specify connection name in Auth0 log-in (for email login)
- Enhance ng-auth to call logout API in Identity service
  (https://app.asana.com/0/100297043256537/100297043256575)
  - Add invokation of "DELETE /v3/authorizations" api in log-out process
- Enhance ng-auth to handle cookies from Identity service
  (https://app.asana.com/0/100297043256537/100297043256590)
  - To store cookies for legacy apps (tcjwt, tcsso) in storage, which are provided by Identity service

### CODE REVIEW

**Comment by ykohata** [comment]
Hi @aselbie,
Could you please review this PR?

cc: @sudoster

**Comment by aselbie** [comment]
Thanks @ykohata. I had been wanting to remove the dependency on appirio-tech-ng-api-services anyway, so I went ahead and removed that. Otherwise it looks great. You write awesomely idiomatic code.

**Comment by ykohata** [comment]
@aselbie 
Thank you for reviwing!
Can I merge this?

And let me confirm the steps to relase it.

1. create a tag on master
2. create a release from the tag
3. publish the relase

It's great if you have a chance to check and support if necessary.
Thanks!
fyi: @sudoster

**Comment by aselbie** [comment]
Yes. Once you create a release Travis should pick it up and automatically publish it to npm.

**Comment by ykohata** [comment]
@aselbie 
Got it. Thanks!

**Pull request merged**
